language: node_js
node_js:
- '10'
- '8'
- '6'
install:
- npm install
script:
- npm run test
- npm run lint
after_success:
- npm install -g codecov
- codecov
deploy:
  provider: npm
  email: kei.itof@gmail.com
  api_key:
    secure: EWtD4ji392jtw86ni38loYqbPzJ5pj3p1cTbEFiCwMmteSydP6/lqbUJMUVzW+5JtbU5DMAU5laU2d4xU5qm7B7CBgbPuN5snEwwW0SJ6JIiuOOGJYQgXeIsG1X7cUGoWOF1jxJt6cOvduS6HO8xFKWUnT3gCxzOD4XhUOuqMZzFfkw0TDGZ0u6DMkYwk1X/qkvrxuV1h61uk9gYHXFEViS6SCOcvAvCq2Ur5/85cDl1NR9BnLuv6OBzFNzjfgpG4cvGJVlYn1QHejYG7c1UbeY5n8kj9/R8QBb6L5eiX9hK29okayGDe5oGj8YevFZwe6l6LsmLWZ7PPBJmtojYpn13dv2K2UdRSAhzZL8t7DYX5Z65CU0zkt66N1JiRtW9ObaBYiIGxn+0RtCQw4hlPmuEkFhlkUaNOhIB/HeTGvW8VWj3yD35YVV5x2QrJPwZ4dYYwom8pCwodFm80SL6e8DzPTIaQIrDjF5Svfva73PSEQJRE4sLyQ98LOMVtn3ZA5dwkEbPe65Ani4UtwxBMxYux52sFO0nb9sY3qC1P+XZF8kOgkPc/H4xxP3cvxYjxrRIB86x1eodkk5pSdQe5Bf14mcNjha8sROld1PW2Gt8bRwK3Ce8VQKWOUG/RRj54JHwTK9RzzdG1NU/+UCbdSPWzWoxfo13G6VXhVXjdvw=
  on:
    tags: true
    repo: kei-ito/gulp-fun
