language: node_js
cache: npm
os: osx
node_js: '12'
install:
  - npm ci
  - npm run build
script:
  - npm install -g codecov c8
  - c8 npm run test
  - c8 report --reporter=text-lcov > coverage.lcov
  - codecov --disable=gcov
  - nvm install 10
  - npm install -g codecov c8
  - c8 npm run test
  - c8 report --reporter=text-lcov > coverage.lcov
  - codecov --disable=gcov
  - nvm install 8
  - npm install -g codecov nyc
  - nyc npm run test
  - codecov --disable=gcov
